#!/bin/bash

#SBATCH --partition=256GB 		# partition name
#SBATCH --time=1-00:00 		# hours:minutes runlimit after which job will be killed
#SBATCH --array=0-9
#SBATCH --nodes=1
#SBATCH --job-name 30-mutation-counter-parallel-array		# Job name
#SBATCH -o ./log/20230403/30-mutation-counter-parallel-array-%j-%a.out		# File to which standard out will be written
#SBATCH -e ./log/20230403/30-mutation-counter-parallel-array-%j-%a.err 		# File to which standard err will be written
cat src/30-mutation-counter-parallel-array.run | perl -ne ' print "# ".$_ ' - >>/dev/stderr
printf "\n############################ END OF SOURCE SCRIPT #######################\n\n" >&2

source /home2/s414024/.bashrc

PROJECT_PATH="/project/greencenter/Toprak_lab/shared/TolC-Mutagenesis"
EXP_ID="20230403"

conda activate toprak-ngs

DIRECTORY="$PROJECT_PATH/data/$EXP_ID/alignment/bowtie2-single"
FASTA="$PROJECT_PATH/data/reference/TolC-oxb14-amplicon.fasta"
OUTPUT_FOLDER="$PROJECT_PATH/dump/$EXP_ID/mutation-tables-single"
CONTIG="TolC-oxb14-amplicon"

mkdir -p $OUTPUT_FOLDER
cd $PROJECT_PATH


FILES=($DIRECTORY/*.bam)
SAMPLE_PATH=${FILES[$SLURM_ARRAY_TASK_ID]}
SAMPLE=${SAMPLE_PATH##*/}
SAMPLE=${SAMPLE%.bam}

python3 src/30-mutation-counter.py   \
--bam $SAMPLE_PATH                   \
--fasta $FASTA                       \
--contig $CONTIG                     \
--start-codon-pos 100                 \
--stop-codon-pos 1581                 \
--base-quality-filter 30             \
--output $OUTPUT_FOLDER/$SAMPLE      
    
echo "$SAMPLE nucleotide changes counted." >>/dev/stderr